Products page
Manju-sree/Brushsy_mart pull request #2
Opened 2022-02-15 14:28 UTC by Manju-sree

Product Listing Page
-  a product listing page where all the products are listed with a section of filters.
- added multiple filters on the product listing page including,
1. Price: A radio button to sort from low to high & high to low.
2. Category: A checkbox with various categories .
3. Ratings: A slider for ratings.
-  added button to clear filters from where we can clear all the applied filters.
- On the product cards, added two call-to-action buttons,
1. Add to Cart
2. Add to Wishlist

2022-02-15 14:43 UTC, sks-21 approved these changes
Rest everything looks nice. Good to merge.

2022-02-15 14:43 UTC, sks-21 commented on css/products.css
> +} */
Remove the unnecessary commented code.

2022-02-15 14:44 UTC, sks-21 commented on pages/products.html
> +    </div>
Just one suggestion, check the functionality of the footer on this page. It overlaps the sidebar.

2022-02-15 14:48 UTC, dev-enforced requested changes
The code looks good to me. Suggested some minor changes after which you can merge

2022-02-15 14:48 UTC, dev-enforced commented on css/products.css
> +button.link-no-style {
Instead of passing this class to the button where you want to apply this style you can simply write .link-no-style for this purpose. One more thing in this class we are having font-size as 1rem and name of the class implies something different so you can check it out

2022-02-15 14:48 UTC, dev-enforced commented on css/products.css
> +.filter-section input {
You can rename this class as .filter-section-input and pass it in the HTML files to that appropriate input element as per your requirements

2022-02-15 14:48 UTC, dev-enforced commented on css/products.css
> +    /* background-color: var( --light-pink-color); */
Remove comments

2022-02-15 14:48 UTC, dev-enforced commented on css/products.css
> +    row-gap: 3.5rem;
You can use a shorthand property for these gap values thus reducing the lines of code. Here grid-gap might be of use

2022-02-15 14:48 UTC, dev-enforced commented on pages/products.html
> +                        <li><a href="" class="link">Twitter</a></li>
Do not keep these links empty

2022-02-15 14:48 UTC, Manju-sree commented on css/products.css
> +} */
thanks for finding out.. will remove it

2022-02-15 15:16 UTC, Manju-sree commented on css/products.css
> +button.link-no-style {
i forgot to remove it.. actually .link-no-style is inherited from css library.

2022-02-16 04:39 UTC, dev-enforced approved these changes
Looks good to me You can merge it @Manju-sree !!

2022-02-16 09:03 UTC, merged